version: "3.9"  # 指定 Docker Compose 文件的版本

services:
  app:
    build:
      context: .  # 設置構建上下文為當前目錄
      args:
        - DEV=true
    ports:
      - "8000:8000"  # 將容器的 8000 端口映射到主機的 8000 端口
    volumes:
      - ./app:/app  # 將主機的 ./app 目錄掛載到容器的 /app 目錄
    command: >  # 執行命令啟動 Django 開發伺服器
      sh -c "python manage.py runserver 0.0.0.0:8000" 
